### ISSUE TITLE
How to use version 1.0.5.

### ISSUE THREAD

**Issue by fdamata** [blefo/FSRLearning#2]
I am trying to use the pack, but when I call Feature_Selector_RL,  I receive an error asking me more arguments. I dont know If I miss some step, but I am follow instructions on README.md. what is the Python version that It was designed?

**Comment by blefo** [comment]
Could you please provide me with screenshots of the error and the code you are trying to use so that I can reproduce the problem.

Thank you!

**Comment by JayTicku** [comment]
I have also had the same issue. Looking at the source code, it seems that the files from the Pypi package do not match the files found on this GitHub repository, making the documentation found on the README.md invalid. Could you release a new version of the Pypi package that matches this GitHub repository?

**Comment by fdamata** [comment]
I did a clone and understand the logic. So, we need do some transformations to become X as a dataframe with header start with 0 until len(columns). I would like to suggest chance It, because on the end with need know the label of Features that were selected. Other question, I think interested use It for regression also (not only for classificar). Congratulations for your job.

About the privously error, I suggest you try implement It dont using git clone, but installing from PIP and doing what were suggested on README.

**Comment by JayTicku** [comment]
I made a fork of this repository and fixed all the errors I could find. I fixed some import errors and added in some pandas logic to fix the slicing of the DataFrame. I also implemented some new changes such as checking for duplicates in the DataFrame after making a slice of it as shrinking the number of columns tends to create many duplicates that can lead to increased training time and overfitting. I also changed the evaluation metric to be balanced accuracy for classification models and r2 score for regression models. Finally, I added in 5-fold cross validation to get a more accurate score. I also updated the README.md to be accurate to the fork. Currently, my fork of this repository works as expected on my system with no errors. Please tell me what you think of the fork.

**Comment by fdamata** [comment]
To use It with a regression, what should be done? The headers should be also as numbers? How the code knows If It os to used to classification or regression?

**Comment by JayTicku** [comment]
You can pass a regressor to the fit_predict() method and it will work for regression problems. You can do feature_selector.fit_predict(X, y, regressor).

**Comment by blefo** [comment]
The package has been updated and released with version 1.0.7. 

Thanks @JayTicku for your valuable contribution.
